name: Dependencies

on:
  repository_dispatch:
    types:
      - update-dependencies
  schedule:
    # Run on daily schedule at 10pm UTC
    - cron: 0 22 * * *

concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  issues: write
  pull-requests: write

env:
  NODE_VERSION: 20

jobs:
  upgrade-dependencies:
    name: 🏗️ Upgrade dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Git Setup
        run: |
          git config --global user.name "Dependency update bot"
          git config --global user.email bot@julianburr.de
          git config --global push.autoSetupRemote true

      - name: Switch to update branch + create it if it doesn't exist yet
        run: |
          git fetch origin
          git switch -c chore/dependency-upgrades

      - name: Reset branch to main origin HEAD, we always want this branch to start from scratch
        run: |
          git reset --hard origin/main

      - name: Upgrade package json & run install to update yarn.lock
        run: |
          npx npm-check-updates -u
          yarn --force

      - name: Commit and push changes to upgrade branch
        run: |
          git commit -m 'chore: Upgrade dependencies'
          git push -f
