name: Production

on:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: true

permissions:
  issues: write
  pull-requests: write

env:
  NODE_VERSION: 20

jobs:
  tests:
    name: 🧪 Run tests and linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout shared actions repo
        uses: actions/checkout@master
        with:
          repository: julianburr/github-actions
          path: ./.github/shared

      - name: Install actions dependencies
        shell: bash
        run: yarn --cwd=.github/shared

      - name: Cache node modules
        uses: ./.github/shared/cache-node-modules

      - name: Install dependencies
        run: yarn

      - name: Run linter, tests and type checks
        run: |
          yarn lint
          yarn test
          yarn typecheck

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout shared actions repo
        uses: actions/checkout@master
        with:
          repository: julianburr/github-actions
          path: ./.github/shared

      - name: Install actions dependencies
        shell: bash
        run: yarn --cwd=.github/shared

      - name: Cache node modules
        uses: ./.github/shared/cache-node-modules

      - name: Install dependencies
        run: yarn

      - name: Deploy app to vercel
        id: deploy
        uses: ./.github/shared/vercel-deploy-app
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          is-production: true
